spring:
  profiles:
    group:
      "local": "localDB"
      "dev": "devDB"
---
spring:
  config:
    activate:
      on-profile: "localDB"
  datasource:
    url: jdbc:h2:mem:test
    username: local
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      schema-locations: "classpath:/schema.sql"
      data-locations: "classpath:/data.sql"
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}
      password: ${LOCAL_REDIS_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: "devDB"
  datasource:
    url: ${MARIADB_URL}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jpa:
    generate-ddl: false
    show-sql: true
